# use `just docs` to build locally or on CI
# use `mkdocs serve` for live preview

site_name: cryptography-kotlin
site_author: Oleg Yukhnevich
site_description: "Type-safe Multi-platform cryptography kotlin library"
site_url: https://whyoleg.github.io/cryptography-kotlin/

repo_name: cryptography-kotlin
repo_url: https://github.com/whyoleg/cryptography-kotlin
edit_uri: edit/main/docs/
remote_branch: gh-pages

copyright: 'Copyright &copy; 2025 Oleg Yukhnevich'

nav:
  - 'Overview':
      - index.md
  - 'Getting Started':
      - getting-started/index.md
      - 'Choosing a Provider':
          - getting-started/providers/index.md
          - 'JDK': getting-started/providers/jdk.md
          - 'Apple': getting-started/providers/apple.md
          - 'WebCrypto': getting-started/providers/webcrypto.md
          - 'OpenSSL3': getting-started/providers/openssl3.md
      - 'Dependency Management': getting-started/dependency-management.md
  - 'Algorithms': algorithms.md
  - 'Examples': examples.md
  - 'Changelog': changelog.md
  - 'API': api/index.html

theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: 'white'
      accent: 'deep purple'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: 'black'
      accent: 'deep purple'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Inter'
    code: 'JetBrains Mono'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.sections
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
    - content.tabs.link

markdown_extensions:
  - smarty
  - tables
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - toc:
      permalink: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/why_oleg
    - icon: fontawesome/brands/telegram
      link: https://t.me/why_oleg
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/why_oleg
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/whyoleg/
