name: Feature Request
description: Suggest a new feature or improvement
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like
      placeholder: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas on how this could be implemented
      placeholder: |
        ```kotlin
        // Example API
        ```

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
