name: Build branch
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - dev
      - kotlin-eap/*

jobs:
  build:
    uses: ./.github/workflows/run-build.yml
  default-tests:
    uses: ./.github/workflows/run-tests-default.yml
  compatibility-tests:
    uses: ./.github/workflows/run-tests-compatibility.yml
