name: Build dev
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/run-build.yml

  default-tests:
    needs: [ build ]
    uses: ./.github/workflows/run-tests-default.yml

  compatibility-tests:
    needs: [ build ]
    uses: ./.github/workflows/run-tests-compatibility.yml

  publish:
    needs: [ default-tests, compatibility-tests ]
    uses: ./.github/workflows/publish-snapshot.yml
    secrets: inherit

  build-docs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - uses: ./.github/actions/setup-gradle
      - name: Build documentation
        uses: gradle/gradle-build-action@v2
        with:
          arguments: mkdocsBuild
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: site
