name: Kotlin EAP CI
on:
  workflow_dispatch:
    inputs:
      kotlinVersion:
        description: 'Kotlin version'
        required: false
        default: '2.1.0-dev-+'

  schedule:
    - cron: '0 0 * * MON'

defaults:
  run:
    shell: bash

jobs:
  kotlin-eap:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        kotlin-version: [ '', '${{ inputs.kotlinVersion }}' ]
        try-next: [ 'true', 'false' ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
        with:
          cache-disabled: true

      - run: >
          ./gradlew
          build publishToMavenLocal
          --continue
          -Pckbuild.skipTestTasks=true
          -Pckbuild.warningsAsErrors=false
          -Pckbuild.kotlinVersionOverride=${{ matrix.kotlin-version }}
          -Pkotlin.experimental.tryNext=${{ matrix.try-next }}
