name: Publish release
on: [ workflow_call ]

jobs:
  publish:
    if: github.repository == 'whyoleg/cryptography-kotlin'
    runs-on: macos-latest
    concurrency:
      group: publish-release
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-gradle
        with:
          cache-disabled: true

      - name: Publish to Maven Local (prepare packages)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal -Pversion=${{ github.ref_name }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.signingKey}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.signingPassword}}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.sonatypeUsername}}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.sonatypePassword}}

      - name: Publish release to Maven Central
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToMavenCentralRepository -Pversion=${{ github.ref_name }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.signingKey}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.signingPassword}}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.sonatypeUsername}}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.sonatypePassword}}
