name: Build website
on:
  workflow_dispatch:
  workflow_call:

jobs:
  website:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      # install just and dependencies for mkdocs-material
      - run: brew install just cairo freetype libffi libjpeg libpng zlib pngquant
      - run: pip install mkdocs-material "mkdocs-material[imaging]"
      - run: brew install just
      - uses: ./.github/actions/setup-environment

      - name: Build documentation
        run: just docs
        env:
          # see https://squidfunk.github.io/mkdocs-material/plugins/requirements/image-processing/#cairo-library-was-not-found
          DYLD_FALLBACK_LIBRARY_PATH: /opt/homebrew/lib

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
