name: Run checks
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-project:
    uses: ./.github/workflows/run-build-project.yml
    permissions:
      contents: write

  build-website:
    needs: [ build-project ]
    uses: ./.github/workflows/run-build-website.yml

  default-tests:
    needs: [ build-project ]
    uses: ./.github/workflows/run-tests-default.yml

  asn1-tests:
    needs: [ build-project ]
    uses: ./.github/workflows/run-tests-asn1.yml

  compatibility-tests:
    needs: [ default-tests, asn1-tests ]
    uses: ./.github/workflows/run-tests-compatibility.yml

  slow-tasks:
    needs: [ compatibility-tests ]
    uses: ./.github/workflows/run-slow-tasks.yml
