name: Run compatibility tests
on: [ workflow_call ]

jobs:
  generate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        target: [ 'jvmAll', 'js', 'native' ]
        include:
          - os: 'macos-latest'
            target: 'native'
          - os: 'windows-latest'
            target: 'native'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-gradle
        with:
          cache-read-only: true

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            cryptography-providers-tests-compatibility:${{ matrix.target }}Test
            -Ptests.compatibility.step=Generate
            -Ptesttool.instanceId=${{ matrix.os }}-${{ matrix.target }}
            --continue
            --configuration-cache

      - name: Dump testtool server-storage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            dumpTesttoolServerStorage
            -Ptesttool.instanceId=${{ matrix.os }}-${{ matrix.target }}
      - name: Upload testtool server-storage dump
        uses: actions/upload-artifact@v3
        with:
          name: compatibility-tests-data
          path: build/testtool/server-storage-dump/*.zip
          if-no-files-found: error

  validate:
    needs: [ generate ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        target: [ 'jvmAll', 'js', 'native' ]
        include:
          - os: 'macos-latest'
            target: 'native'
          - os: 'windows-latest'
            target: 'native'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-gradle
        with:
          cache-read-only: true

      - name: Download testtool server-storage dump
        uses: actions/download-artifact@v3
        with:
          name: compatibility-tests-data
          path: build/testtool/server-storage-dump

      - name: Restore testtool server-storage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: restoreTesttoolServerStorage

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            cryptography-providers-tests-compatibility:${{ matrix.target }}Test
            -Ptests.compatibility.step=Validate
            -Ptesttool.instanceId=${{ matrix.os }}-${{ matrix.target }}
            --continue
            --configuration-cache
