name: Run slow tasks
on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  linkNative:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - run: ./gradlew linkNative --continue --no-configuration-cache
